// Usage: npm run posters:fetch   (writes src/data/posters.ts by matching each title against TMDB)
// Requires TMDB_API_KEY in .env.local (themoviedb.org/settings/api).
import { writeFileSync } from "node:fs";
import { POSTERS as EXISTING } from "../src/data/posters.ts";
import { TITLES } from "../src/data/titles.ts";

try {
  process.loadEnvFile(".env.local");
} catch {
  // .env.local is optional here; TMDB_API_KEY may already be in the environment.
}

const apiKey = process.env.TMDB_API_KEY || "";
if (!apiKey) {
  console.error("Missing TMDB_API_KEY. Add it to .env.local (get a free key at themoviedb.org/settings/api).");
  process.exit(1);
}

const IMAGE_BASE = "https://image.tmdb.org/t/p/w500";
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

interface TmdbResult {
  poster_path: string | null;
  title?: string;
  name?: string;
  release_date?: string;
  first_air_date?: string;
}

async function search(kind: "movie" | "tv", query: string, year: string): Promise<TmdbResult | null> {
  const url = new URL(`https://api.themoviedb.org/3/search/${kind}`);
  url.searchParams.set("api_key", apiKey);
  url.searchParams.set("query", query);
  if (kind === "movie") url.searchParams.set("year", year);
  else url.searchParams.set("first_air_date_year", year);

  const res = await fetch(url);
  if (!res.ok) throw new Error(`TMDB ${kind} search failed (${res.status}) for "${query}"`);
  const data = (await res.json()) as { results: TmdbResult[] };
  return data.results?.[0] ?? null;
}

async function findPoster(title: (typeof TITLES)[number]): Promise<string | null> {
  const year = title.release_date.slice(0, 4);
  // "special" entries (e.g. Werewolf by Night) are usually catalogued as TV movies on TMDB.
  const order: Array<"movie" | "tv"> = title.type === "tv" ? ["tv", "movie"] : ["movie", "tv"];
  for (const kind of order) {
    const result = await search(kind, title.title, year);
    if (result?.poster_path) return result.poster_path;
  }
  // Retry without the year filter as a last resort (helps entries with ambiguous/shifted dates).
  for (const kind of order) {
    const result = await search(kind, title.title, "");
    if (result?.poster_path) return result.poster_path;
  }
  return null;
}

async function main() {
  const entries: Array<[string, string]> = [];
  const misses: string[] = [];

  for (const title of TITLES) {
    const existing = EXISTING[title.id];
    if (existing) {
      entries.push([title.id, existing]);
      console.log(`· ${title.title} (kept existing)`);
      continue;
    }
    try {
      const posterPath = await findPoster(title);
      if (posterPath) {
        entries.push([title.id, `${IMAGE_BASE}${posterPath}`]);
        console.log(`✓ ${title.title}`);
      } else {
        misses.push(title.title);
        console.log(`✗ ${title.title} (no match)`);
      }
    } catch (err) {
      misses.push(title.title);
      console.log(`✗ ${title.title} (${(err as Error).message})`);
    }
    await sleep(150); // stay well under TMDB's rate limit
  }

  const body = entries.map(([id, url]) => `  ${JSON.stringify(id)}: ${JSON.stringify(url)},`).join("\n");
  const file = `// Generated by scripts/fetch-posters.ts. Existing entries (including hand-added ones) are kept as-is;\n// only titles missing a poster are looked up on TMDB. Delete a line first to force a re-lookup.\nexport const POSTERS: Record<string, string> = {\n${body}\n};\n`;
  writeFileSync("src/data/posters.ts", file);

  console.log(`\nWrote src/data/posters.ts with ${entries.length}/${TITLES.length} posters.`);
  if (misses.length) {
    console.log(`No match for: ${misses.join(", ")}`);
  }
}

main();
