// Usage: npm run seed:generate   (writes supabase/seed.sql from src/data/titles.ts)
import { writeFileSync, mkdirSync } from "node:fs";
import { TITLES } from "../src/data/titles.ts";

const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);

const values = TITLES.map(
  (t) =>
    `  (${q(t.id)}, ${q(t.title)}, ${q(t.type)}, ${q(t.release_date)}, ${t.story_order_index}, ${t.runtime_minutes}, ${q(t.universe)}, ${q(t.importance)}, ${q(t.poster_url)}, ${t.leads_into_doomsday})`,
).join(",\n");

const sql = `-- Generated by scripts/generate-seed.ts from src/data/titles.ts. Do not edit by hand.
-- Two passes so story_order_index (unique) can be reshuffled safely on re-seed.

update public.titles set story_order_index = -story_order_index;

insert into public.titles
  (id, title, type, release_date, story_order_index, runtime_minutes, universe, importance, poster_url, leads_into_doomsday)
values
${values}
on conflict (id) do update set
  title = excluded.title,
  type = excluded.type,
  release_date = excluded.release_date,
  story_order_index = excluded.story_order_index,
  runtime_minutes = excluded.runtime_minutes,
  universe = excluded.universe,
  importance = excluded.importance,
  poster_url = coalesce(public.titles.poster_url, excluded.poster_url),
  leads_into_doomsday = excluded.leads_into_doomsday;

`;

mkdirSync("supabase", { recursive: true });
writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote supabase/seed.sql with ${TITLES.length} titles`);
