-- 50 more (harder) trivia questions, tagged with a difficulty column. Both tiers stay in the same
-- pool that pickQuestion() draws from at random - this just makes the bank bigger and deeper.
alter table public.trivia_questions add column difficulty text not null default 'normal' check (difficulty in ('normal', 'hard'));
update public.trivia_questions set difficulty = 'normal';

insert into public.trivia_questions (question, options, correct_index, difficulty) values
($$What is the first name of Tony Stark's father?$$, $$["Howard","Harold","Henry","Hank"]$$::jsonb, 0, 'hard'),
($$What metal does Ultron plan to use for his final body in Avengers: Age of Ultron?$$, $$["Adamantium","Vibranium","Uru","Promethium"]$$::jsonb, 1, 'hard'),
($$Who trains Doctor Strange at Kamar-Taj?$$, $$["Wong","Mordo","The Ancient One","Kaecilius"]$$::jsonb, 2, 'hard'),
($$Who is Jane Foster's scientist mentor in Thor (2011)?$$, $$["Ian Boothby","Darcy Lewis","Phil Coulson","Erik Selvig"]$$::jsonb, 3, 'hard'),
($$In what year was the first Iron Man film released?$$, $$["2008","2006","2007","2009"]$$::jsonb, 0, 'hard'),
($$What terrorist organization captures Tony Stark in Iron Man?$$, $$["Hydra","Ten Rings","A.I.M.","The Hand"]$$::jsonb, 1, 'hard'),
($$Who runs the rival weapons company introduced in Iron Man 2?$$, $$["Obadiah Stane","Aldrich Killian","Justin Hammer","Darren Cross"]$$::jsonb, 2, 'hard'),
($$Who is the primary antagonist of Ant-Man (2015)?$$, $$["Justin Hammer","Sonny Burch","Bill Foster","Darren Cross"]$$::jsonb, 3, 'hard'),
($$What gives Black Panther his powers?$$, $$["Heart-Shaped Herb","Golden Orchid","Moon Flower","Sunstone Bloom"]$$::jsonb, 0, 'hard'),
($$Who is revealed to be Peter Quill's father in Guardians of the Galaxy Vol. 2?$$, $$["Thanos","Ego","The Grandmaster","Yondu"]$$::jsonb, 1, 'hard'),
($$Who raised Peter Quill after he was abducted from Earth?$$, $$["Ego","Nova Prime","Yondu Udonta","Ravager Stakar"]$$::jsonb, 2, 'hard'),
($$What is Thanos's homeworld called?$$, $$["Sakaar","Xandar","Zenn-La","Titan"]$$::jsonb, 3, 'hard'),
($$Who is Gamora's adoptive sister?$$, $$["Nebula","Mantis","Kraglin","Ayesha"]$$::jsonb, 0, 'hard'),
($$Who created Rocket Raccoon, revealed in Guardians of the Galaxy Vol. 3?$$, $$["Thanos","The High Evolutionary","Ego","The Collector"]$$::jsonb, 1, 'hard'),
($$What criminal gang does Kate Bishop tangle with in the Hawkeye series?$$, $$["Ten Rings","Hydra","Tracksuit Mafia","Sokovian Resistance"]$$::jsonb, 2, 'hard'),
($$Who is revealed to be the Kingpin in the Hawkeye series?$$, $$["Wilson Grant","William Fisk","Norman Osborn","Wilson Fisk"]$$::jsonb, 3, 'hard'),
($$Who mentors Kate Bishop in the Hawkeye series?$$, $$["Clint Barton","Jack Duquesne","Wilson Fisk","Maya Lopez"]$$::jsonb, 0, 'hard'),
($$Who plays Erik Killmonger in Black Panther?$$, $$["Chadwick Boseman","Michael B. Jordan","Daniel Kaluuya","Winston Duke"]$$::jsonb, 1, 'hard'),
($$What year is Captain America frozen in ice, according to the MCU films?$$, $$["1943","1944","1945","1946"]$$::jsonb, 2, 'hard'),
($$Which Hydra scientist is tied to Bucky Barnes's brainwashing in Captain America: The Winter Soldier?$$, $$["Alexander Pierce","Baron Strucker","Johann Schmidt","Arnim Zola"]$$::jsonb, 3, 'hard'),
($$What happens to the Red Skull at the end of Captain America: The First Avenger?$$, $$["He disappears via the Tesseract","He dies in an explosion","He is captured by SHIELD","He escapes to Wakanda"]$$::jsonb, 0, 'hard'),
($$What does Tony Stark use to snap away Thanos's army in Avengers: Endgame?$$, $$["A golden gauntlet","An Infinity Gauntlet made of nanotech","Odin's gauntlet","A vibranium gauntlet"]$$::jsonb, 1, 'hard'),
($$What is Sylvie's relationship to Loki in the Loki series?$$, $$["His sister","His daughter","A variant of Loki","His mother"]$$::jsonb, 2, 'hard'),
($$Who is revealed to control the timeline at the end of Loki Season 1?$$, $$["Kang the Conqueror","Immortus","Alioth","He Who Remains"]$$::jsonb, 3, 'hard'),
($$What entity made of pure time devours variants at the End of Time in Loki?$$, $$["Alioth","Ego","Galactus","The Void"]$$::jsonb, 0, 'hard'),
($$What is the name of Wanda Maximoff's twin brother?$$, $$["Vision","Pietro Maximoff","Ultron","Erik"]$$::jsonb, 1, 'hard'),
($$What town does WandaVision take place in?$$, $$["Salem","Hex Falls","Westview","New Asgard"]$$::jsonb, 2, 'hard'),
($$What is the witch neighbor "Agnes" really called in WandaVision?$$, $$["Agnes","Dottie","Sharon","Agatha Harkness"]$$::jsonb, 3, 'hard'),
($$What ancient book corrupts Wanda Maximoff in Doctor Strange in the Multiverse of Madness?$$, $$["The Darkhold","The Necronomicon","The Book of Vishanti","The Eye of Agamotto"]$$::jsonb, 0, 'hard'),
($$What is the name of the multiversal group of variants Doctor Strange meets on Earth-838?$$, $$["The Watchers","The Illuminati","The TVA","The Masters of the Mystic Arts"]$$::jsonb, 1, 'hard'),
($$Who plays Captain Carter in Doctor Strange in the Multiverse of Madness?$$, $$["Elizabeth Olsen","Rachel McAdams","Hayley Atwell","Xochitl Gomez"]$$::jsonb, 2, 'hard'),
($$What country is tied to Kamala Khan's family history and the origin of her powers?$$, $$["India","Afghanistan","Bangladesh","Pakistan"]$$::jsonb, 3, 'hard'),
($$What object grants Kamala Khan her powers in the Ms. Marvel series?$$, $$["A bangle","A ring","A necklace","A sword"]$$::jsonb, 0, 'hard'),
($$What organization does Shang-Chi's father lead?$$, $$["Hydra","The Ten Rings","A.I.M.","The Hand"]$$::jsonb, 1, 'hard'),
($$What creature does the Great Protector become to fight the Dweller-in-Darkness in Shang-Chi?$$, $$["A phoenix","A tiger","A dragon","A serpent"]$$::jsonb, 2, 'hard'),
($$What is the name of Shang-Chi's father, leader of the Ten Rings?$$, $$["Xu Xialing","Han Wenwu","Jiang Li","Xu Wenwu"]$$::jsonb, 3, 'hard'),
($$Who is Shang-Chi's sister, who runs an underground fight club?$$, $$["Xu Xialing","Katy Chen","Xu Wenwu","Jiang Li"]$$::jsonb, 0, 'hard'),
($$Who rules the underwater nation of Talokan in Black Panther: Wakanda Forever?$$, $$["K'uk'ulkan","Namor","Attuma","Krang"]$$::jsonb, 1, 'hard'),
($$Who becomes the new Black Panther at the end of Wakanda Forever?$$, $$["Okoye","Nakia","Shuri","M'Baku"]$$::jsonb, 2, 'hard'),
($$Which MIT student builds a vibranium detector in Black Panther: Wakanda Forever?$$, $$["Shuri","Nakia","Okoye","Riri Williams"]$$::jsonb, 3, 'hard'),
($$What is Riri Williams's superhero alias?$$, $$["Ironheart","War Machine","Iron Maiden","Rescue"]$$::jsonb, 0, 'hard'),
($$Who plays Valkyrie in Thor: Ragnarok?$$, $$["Cate Blanchett","Tessa Thompson","Karen Gillan","Zoe Saldana"]$$::jsonb, 1, 'hard'),
($$What planet does Thor get stranded on in Thor: Ragnarok?$$, $$["Xandar","Contraxia","Sakaar","Vormir"]$$::jsonb, 2, 'hard'),
($$What is the title of Jeff Goldblum's character who rules Sakaar?$$, $$["The Collector","The Elder","The Overseer","The Grandmaster"]$$::jsonb, 3, 'hard'),
($$What weapon does Thor obtain to replace Mjolnir?$$, $$["Stormbreaker","Gungnir","Jarnbjorn","Odinsword"]$$::jsonb, 0, 'hard'),
($$What realm is Stormbreaker forged in during Avengers: Infinity War?$$, $$["Sakaar","Nidavellir","Asgard","Muspelheim"]$$::jsonb, 1, 'hard'),
($$Who is the dwarf king that helps forge Stormbreaker?$$, $$["Sindri","Brokk","Eitri","Dvalin"]$$::jsonb, 2, 'hard'),
($$What alien army invades New York in The Avengers (2012)?$$, $$["Skrulls","Kree","Frost Giants","Chitauri"]$$::jsonb, 3, 'hard'),
($$What species is the villain Ronan the Accuser?$$, $$["Kree","Skrull","Xandarian","Sakaaran"]$$::jsonb, 0, 'hard'),
($$What military unit does Carol Danvers believe she serves in before learning the truth in Captain Marvel?$$, $$["S.H.I.E.L.D.","Starforce","The Ten Rings","Nova Corps"]$$::jsonb, 1, 'hard');
