// Generated by scripts/fetch-posters.ts. Run `npm run posters:fetch` (needs TMDB_API_KEY in .env.local)
// to fill this in. Entries added by hand (like the one below) are left alone on re-run since the script
// only ever adds a title it doesn't already have a line for.
export const POSTERS: Record<string, string> = {
  "captain-america-the-first-avenger":"https://thumb.wikimedia.org/wikipedia/en/thumb/3/37/Captain_America_The_First_Avenger_poster.jpg/250px-Captain_America_The_First_Avenger_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "eyes-of-wakanda": "https://m.media-amazon.com/images/M/MV5BZjhhOTE5ODgtNDFjOS00ZTdlLTgzYjAtNGU1NmM4YzkwYWMxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "captain-marvel": "https://m.media-amazon.com/images/M/MV5BZDI1NGU2ODAtNzBiNy00MWY5LWIyMGEtZjUxZjUwZmZiNjBlXkEyXkFqcGc@._V1_.jpg",
  "iron-man": "https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
  "iron-man-2": "https://a.ltrbxd.com/resized/film-poster/4/6/5/1/1/46511-iron-man-2-0-600-0-900-crop.jpg?v=67e856ad63",
  "the-incredible-hulk":"https://upload.wikimedia.org/wikipedia/en/f/f0/The_Incredible_Hulk_%28film%29_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
  "thor": "https://m.media-amazon.com/images/M/MV5BNjRhNGZjZjEtYTQzYS00OWUxLThjNGEtMTIwMTE2ZDFlZTZkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "the-avengers": "https://i.ebayimg.com/images/g/abUAAOSwiSlldA3T/s-l1200.jpg",
  "thor-the-dark-world":"https://thumb.wikimedia.org/wikipedia/en/thumb/7/7f/Thor_The_Dark_World_poster.jpg/250px-Thor_The_Dark_World_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "black-panther":"https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
  "captain-america-the-winter-soldier":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/c0/Captain_America_The_Winter_Soldier_main_poster.jpg/revision/latest?cb=20160617182910",
  "spider-man-brand-new-day":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e8/Spider-Man_Brand_New_Day_Tall_Poster.jpg/revision/latest?cb=20260415024649",
  "guardians-of-the-galaxy":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f8/GuardiansoftheGalaxyTheatricalPoster.jpg/revision/latest?cb=20140516163015",
  "guardians-of-the-galaxy-vol-2":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5c/GOTG2_Payoff_1_Sheet_Online_lg.jpg/revision/latest?cb=20170301052206",
  "guardians-of-the-galaxy-vol-3":
    "https://upload.wikimedia.org/wikipedia/en/7/74/Guardians_of_the_Galaxy_Vol._3_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
  "avengers-age-of-ultron":
    "https://upload.wikimedia.org/wikipedia/en/f/ff/Avengers_Age_of_Ultron_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
  "ant-man-quantumania":
    "https://thumb.wikimedia.org/wikipedia/en/thumb/3/30/Ant-Man_and_the_Wasp_Quantumania_poster.jpg/250px-Ant-Man_and_the_Wasp_Quantumania_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "avengers-infinity-war":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/11/Avengers_Infinity_war_poster.jpeg/revision/latest/scale-to-width-down/1200?cb=20180316141550",
  "avengers-endgame":
    "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/91/Endgame_Poster_2.jpg/revision/latest/scale-to-width-down/1200?cb=20190314215527",
  "doctor-strange":
    "https://thumb.wikimedia.org/wikipedia/en/thumb/a/a1/Doctor_Strange_%282016_film%29_poster.jpg/250px-Doctor_Strange_%282016_film%29_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "doctor-strange-in-the-multiverse-of-madness":
    "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Doctor_Strange_in_the_Multiverse_of_Madness_poster.jpg/250px-Doctor_Strange_in_the_Multiverse_of_Madness_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "ant-man": "https://cdng.europosters.eu/pod_public/750/262956.jpg",
  "iron-man-3": "https://cdn.posteritati.com/posters/000/000/006/634/iron-man-3-md-web.jpg",
  "captain-america-civil-war":
    "https://akns-images.eonline.com/eol_images/Entire_Site/201627/rs_634x940-160307074539-634.captain-america-civil-war-poster-chris-evans-robert-downey-jr.3716.jpg?fit=around%7C776:1151&output-quality=90&crop=776:1151;center,top",
  "black-widow": "https://i.ebayimg.com/00/s/MTYwMFgxMDgw/z/xX4AAOSwfgxg26MH/$_57.JPG?set_id=8800005007",
  "spider-man-homecoming": "https://i.etsystatic.com/47065167/r/il/5c6b67/5627093575/il_1080xN.5627093575_ims6.jpg",
  "black-panther-wakanda-forever":
    "https://m.media-amazon.com/images/M/MV5BYWY5NDY1ZjItZDQxMy00MTAzLTgyOGQtNTQxYjFiMzZjMjUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "captain-america-brave-new-world": "https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
  "spider-man-no-way-home":
    "https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "spider-man-far-from-home": "https://m.media-amazon.com/images/M/MV5BMzNhNTE0NWQtN2E1Ny00NjcwLTg1YTctMGY1NmMwODJmY2NmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "ant-man-and-the-wasp": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzAMaz2IGscVPvLQejBp9Hife2txQGvLX8IZgNdm9NzIgRXD2jq9n8UNQ&s=10",
  "thor-ragnarok": "https://i.ebayimg.com/images/g/7VsAAOSwH35Zn5-g/s-l1200.jpg",
  "loki-s1" : "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p19575003_b_v12_aa.jpg",
  "loki-s2" : "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e5/God_Loki_Tall_Poster.jpg/revision/latest?cb=20231113172425",
  "wandavision" : "https://hips.hearstapps.com/hmg-prod/images/wandavision-br-digital-keyart-v5-lg-1600725440.jpg?resize=980:*",
  "the-falcon-and-the-winter-soldier" : "https://m.media-amazon.com/images/I/81Lt9xp+-xL._AC_UL450_SY450_QL70_.jpg",
  "shang-chi" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_9cNCBR8quzP_6KQdNHSpJ3Sf8WlVgq835y_R2XQmTg&s",
  "the-marvels" : "https://lumiere-a.akamaihd.net/v1/images/56245l11a_goat_philippines_apac_poster_1sht_e357e03a.jpeg?region=0%2C0%2C2592%2C3840",
  "eternals" : "https://cdn.marvel.com/content/1x/eternals_lob_crd_06.webp",
  "hawkeye" : "https://i.redd.it/sfohoarixev71.jpg",
  "thor-love-and-thunder" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlytuTBjWE9njkKRA-XtOWLBYGfY9a9Tf0Ovf4fKfShVBaJgrKzf50b99c&s=10",
  "thunderbolts" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_WCQXnwTLTNko4oA9PejLi3vis9m5BS6HJV0bp13bA&s",
  "ironheart" : "https://i.ebayimg.com/images/g/QgEAAOSwA3toN1Fs/s-l1200.jpg",
  "guardians-holiday-special" : "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/79/Guardians_Holiday_Special_Poster.jpg/revision/latest?cb=20250228035811",
  "deadpool-and-wolverine" : "https://thumb.wikimedia.org/wikipedia/en/thumb/4/4c/Deadpool_%26_Wolverine_poster.jpg/250px-Deadpool_%26_Wolverine_poster.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
  "agatha-all-along" : "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/eafb5739-e9db-4a02-bc09-9b88be835ea5/di70i2v-28c245ae-43b5-4ea8-b091-b08480cd6009.jpg/v1/fill/w_1600,h_2370,q_75,strp/agatha_all_along___poster_2_by_iconuser123_di70i2v-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiIvZi9lYWZiNTczOS1lOWRiLTRhMDItYmMwOS05Yjg4YmU4MzVlYTUvZGk3MGkydi0yOGMyNDVhZS00M2I1LTRlYTgtYjA5MS1iMDg0ODBjZDYwMDkuanBnIiwiaGVpZ2h0IjoiPD0yMzcwIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uud2F0ZXJtYXJrIl0sIndtayI6eyJwYXRoIjoiL3dtL2VhZmI1NzM5LWU5ZGItNGEwMi1iYzA5LTliODhiZTgzNWVhNS9pY29udXNlcjEyMy00LnBuZyIsIm9wYWNpdHkiOjk1LCJwcm9wb3J0aW9ucyI6MC40NSwiZ3Jhdml0eSI6ImNlbnRlciJ9fQ.2q-DjvhXjjW2-1JmBgjFKHf74ax1eP6twGi-jpHK9Nk",
  "the-fantastic-four-first-steps" : "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/8c/The_Fantastic_Four_First_Steps_Final_Poster_Tall.jpg/revision/latest/thumbnail/width/360/height/360?cb=20250625151837",
  "secret-invasion" : "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/72/Secret_Invasion_S01_Poster.jpg/revision/latest?cb=20230728222509",
  "logan" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7be3Ay5s2Ra5gbpuXbS1-2yDgbMv_LTCrjs-hrZNvxoUQlu1P_GYb5hU&s=10",
  "deadpool" : "https://i.ebayimg.com/images/g/5uMAAOSw4GVYUdGK/s-l1200.jpg",
  "deadpool-2" : "https://theposterdepot.com/cdn/shop/products/deadpool2ptr08201901_ed167c6b-48fa-43f0-a7a9-bdc094e37926_580x.jpg?v=1754777660",
  "the-amazing-spider-man" : "https://m.media-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_.jpg",
  "the-amazing-spider-man-2" : "https://image.tmdb.org/t/p/original/c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg",
  "spider-man-2002" : "https://i.pinimg.com/564x/ff/04/09/ff040973490228536c2da47d9d5fbe6a.jpg",
  "spider-man-2" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP9529aRImJ6oOCAolLbOBcJC8qHyfw7dJbV1wnofYK4pqFj7rj-lTnRs&s=10",
  "spider-man-3" : "https://m.media-amazon.com/images/M/MV5BODE2NzNhMDctYjUzMC00Y2M5LWI2Y2EtODJkZTFjN2Y5ODlmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "x-men" : "https://i.ebayimg.com/images/g/ptQAAOSw44BYi5DD/s-l1200.jpg",
  "x2-x-men-united" : "https://closeup.de/cdn/shop/files/G765922.jpg?v=1748296887&width=1500",
  "x-men-the-last-stand" : "https://m.media-amazon.com/images/M/MV5BMThmOWE3OWEtODJmNC00ZDEzLTk4MWUtNzEzM2RiNmJiZmU3XkEyXkFqcGc@._V1_.jpg",
  "x-men-origins-wolverine" : "https://m.media-amazon.com/images/M/MV5BZjQwOGEzNjUtNDgwYS00NzUzLWJhZjAtNmFlNzY2YTQyOTllXkEyXkFqcGc@._V1_.jpg",
  "x-men-first-class" : "https://m.media-amazon.com/images/M/MV5BMTg5OTMxNzk4Nl5BMl5BanBnXkFtZTcwOTk1MjAwNQ@@._V1_FMjpg_UX1000_.jpg",
  "the-wolverine" : "https://i.ebayimg.com/images/g/Fh8AAOSwa55cOhNr/s-l400.jpg",
  "x-men-days-of-future-past" : "https://cdng.europosters.eu/pod_public/750/263559.jpg",
  "x-men-apocalypse" : "https://m.media-amazon.com/images/M/MV5BNjVhNWY3NjItNmZjOS00NTU3LWFiZTctNzdjNGM5Y2Y0MDUwXkEyXkFqcGc@._V1_.jpg",
  "dark-phoenix" : "https://cdn.marvel.com/content/2x/darkphoenix_poster_web_1.webp"
};
